In [1]:
import pandas as pd
s=pd.Series(['A','X','E','B','D'])
res=pd.get_dummies(s)
print(res)

       A      B      D      E      X
0   True  False  False  False  False
1  False  False  False  False   True
2  False  False  False   True  False
3  False   True  False  False  False
4  False  False   True  False  False

In [12]:
import pandas as pd
df=pd.DataFrame({"name":['A','B','C','D'],"Department":["CS","IT","CS","EC"]})
res=pd.get_dummies(df,columns=["Department"],)
print(res)

  name  Department_CS  Department_EC  Department_IT
0    A           True          False          False
1    B          False          False           True
2    C           True          False          False
3    D          False           True          False

In [13]:
import numpy as np
df=pd.DataFrame({"Score":[45,70,80,55]})
df["Result"] = np.where(df["Score"]>=60,"Pass","Fail")
df

   Score Result
0     45   Fail
1     70   Pass
2     80   Pass
3     55   Fail

In [16]:
df=pd.DataFrame({"Score":[45,70,80,55]})
df["Grade"]=np.where(df["Score"]>=75,"A",np.where(df["Score"]>=60,"B","C"))
df

   Score Result Grade
0     45   Fail     C
1     70   Pass     B
2     80   Pass     A
3     55   Fail     C

In [21]:
import numpy as np
df=pd.DataFrame({"area":[1200,1500,1800,2200,2500],"price":[1500000,2200000,3100000,2800000,1800000]})
df["Grade"]=np.where(df["price"]<=2000000,"Low",np.where(df["price"]<=3000000,"Medium","High"))
df

   area    price   Grade
0  1200  1500000     Low
1  1500  2200000  Medium
2  1800  3100000    High
3  2200  2800000  Medium
4  2500  1800000     Low

In [34]:
from sklearn.model_selection import train_test_split
df=pd.DataFrame({"Hours":[1,2,3,4,5,6],"Score":[50,55,65,70,80,90]})
x=df[["Hours"]]
y=df["Score"]
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=60)
print(X_train)
print(X_test)
print(y_train)
print(y_test)

   Hours
3      4
2      3
1      2
5      6
   Hours
0      1
4      5

3    70
2    65
1    55
5    90
Name: Score, dtype: int64
0    50
4    80
Name: Score, dtype: int64

In [44]:
import pandas as pd
df=pd.read_csv("ipl-matches.csv")
df

          ID        City        Date  ...                                       Team2Players        Umpire1         Umpire2
0    1312200   Ahmedabad  2022-05-29  ...  ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...    CB Gaffaney     Nitin Menon
1    1312199   Ahmedabad  2022-05-27  ...  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...    CB Gaffaney     Nitin Menon
2    1312198     Kolkata  2022-05-25  ...  ['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...  J Madanagopal        MA Gough
3    1312197     Kolkata  2022-05-24  ...  ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...   BNJ Oxenford       VK Sharma
4    1304116      Mumbai  2022-05-22  ...  ['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...   AK Chaudhary   NA Patwardhan
..       ...         ...         ...  ...                                                ...            ...             ...
945   335986     Kolkata  2008-04-20  ...  ['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...      BF Bowden     K Hariharan
946   335985      Mumbai  2008-04-20  ...  ['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...       SJ Davis       DJ Harper
947   335984       Delhi  2008-04-19  ...  ['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...      Aleem Dar  GA Pratapkumar
948   335983  Chandigarh  2008-04-19  ...  ['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...      MR Benson      SL Shastri
949   335982   Bangalore  2008-04-18  ...  ['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...      Asad Rauf     RE Koertzen

[950 rows x 20 columns]

In [68]:
import pandas as pd
df=pd.read_csv("ipl-matches.csv")
res=df.loc[(((df["Team1"]=="Royal Challengers Bangalore")
             &(df["Team2"]=="Kolkata Knight Riders"))
            |((df["Team2"]=="Royal Challengers Bangalore")
              &(df["Team1"]=="Kolkata Knight Riders")))
    &(df["WinningTeam"]=="Royal Challengers Bangalore")]
res

          ID       City        Date  ...                                       Team2Players         Umpire1         Umpire2
68   1304052     Mumbai  2022-03-30  ...  ['F du Plessis', 'Anuj Rawat', 'V Kohli', 'DJ ...   J Madanagopal   Navdeep Singh
124  1254067    Chennai  2021-04-18  ...  ['N Rana', 'Shubman Gill', 'RA Tripathi', 'EJG...   C Shamshuddin     Nitin Menon
155  1216494  Abu Dhabi  2020-10-21  ...  ['D Padikkal', 'AJ Finch', 'Gurkeerat Singh', ...       VK Sharma          S Ravi
166  1216540        NaN  2020-10-12  ...  ['T Banton', 'Shubman Gill', 'N Rana', 'EJG Mo...  RK Illingworth    K Srinivasan
219  1178410    Kolkata  2019-04-19  ...  ['CA Lynn', 'SP Narine', 'Shubman Gill', 'RV U...        IJ Gould     Nitin Menon
385   980995    Kolkata  2016-05-16  ...  ['CH Gayle', 'V Kohli', 'AB de Villiers', 'SR ...     CB Gaffaney  A Nand Kishore
459   829771  Bangalore  2015-05-02  ...  ['RV Uthappa', 'G Gambhir', 'AD Russell', 'RN ...       JD Cloete       PG Pathak
487   829713    Kolkata  2015-04-11  ...  ['CH Gayle', 'V Kohli', 'KD Karthik', 'Mandeep...          S Ravi   C Shamshuddin
616   598008  Bangalore  2013-04-11  ...  ['MS Bisla', 'G Gambhir', 'JH Kallis', 'YK Pat...       Asad Rauf    AK Chaudhary
717   501255  Bangalore  2011-05-14  ...  ['JH Kallis', 'EJG Morgan', 'G Gambhir', 'MK T...     RE Koertzen       RB Tiffin
751   501222    Kolkata  2011-04-22  ...  ['TM Dilshan', 'CH Gayle', 'V Kohli', 'AB de V...       SS Hazare       RB Tiffin
792   419148  Bangalore  2010-04-10  ...  ['SC Ganguly', 'CH Gayle', 'BB McCullum', 'MK ...     K Hariharan       DJ Harper
853   392221  Centurion  2009-05-12  ...  ['BB McCullum', 'SC Ganguly', 'AN Ghosh', 'DJ ...       M Erasmus       SS Hazare
875   392199     Durban  2009-04-29  ...  ['BB McCullum', 'CH Gayle', 'BJ Hodge', 'SC Ga...       MR Benson  TH Wijewardene

[14 rows x 20 columns]